# Generated by Django 5.2.7 on 2025-10-17 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('org_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField()),
                ('org_url', models.URLField()),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organizations')),
            ],
        ),
    ]
