# Generated by Django 5.2.7 on 2025-10-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='org_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
