# Generated by Django 5.2.7 on 2025-10-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizations_org_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizations.organizations'),
        ),
    ]
