# Generated by Django 5.2.7 on 2025-10-17 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizations_parent_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_firstname', models.CharField()),
                ('contact_lastname', models.CharField()),
                ('contact_title', models.CharField()),
                ('contact_department', models.CharField()),
                ('contact_phone_desk', models.CharField()),
                ('contact_phone_mobile', models.CharField()),
                ('contact_phone_fax', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='StreetAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(help_text='Street name and building/house number (e.g., 123 Main St)', max_length=100, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, or box number (optional)', max_length=100, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='United States', help_text='Country name', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Street Addresses',
            },
        ),
        migrations.AddField(
            model_name='organizations',
            name='org_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizations.streetaddress'),
        ),
    ]
