# Generated by Django 5.2.7 on 2025-10-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_contacts_streetaddress_organizations_org_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Organizations',
            new_name='Organization',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
