# Generated by Django 5.2.7 on 2025-10-17 15:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_rename_contacts_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_department',
            field=models.CharField(help_text='Deparment within the organization', verbose_name='Deparment'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_firstname',
            field=models.CharField(help_text='First Name', verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_lastname',
            field=models.CharField(help_text='Last Name', verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone_desk',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', unique=True, verbose_name='Desk Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone_fax',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', unique=True, verbose_name='Fax Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', unique=True, verbose_name='Mobile Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_title',
            field=models.CharField(help_text='Title/Position', verbose_name='Title'),
        ),
    ]
