# Generated by Django 5.2.7 on 2025-10-17 15:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_contact_contact_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_department',
            field=models.CharField(blank=True, help_text='Deparment within the organization', null=True, verbose_name='Deparment'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_lastname',
            field=models.CharField(blank=True, help_text='Last Name', null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone_desk',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Title/Position', max_length=128, region='US', unique=True, verbose_name='Desk Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone_fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US', unique=True, verbose_name='Fax Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US', unique=True, verbose_name='Mobile Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Title/Position', null=True, verbose_name='Title'),
        ),
    ]
