# Generated by Django 5.2.7 on 2025-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_contact_contact_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_organizations',
            field=models.ManyToManyField(blank=True, help_text='The organizations this contact is associated with.', related_name='contacts', to='organizations.organization'),
        ),
    ]
