# Generated by Django 5.2.7 on 2025-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_contact_contact_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_firstname',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_lastname',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='parent_org',
            new_name='org_parent',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='date_create',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='E-Mail Address', max_length=254, null=True, verbose_name='E-Mail'),
        ),
    ]
