# Generated by Django 5.2.7 on 2025-11-20 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0010_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('org_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizations.organization')),
            ],
        ),
    ]
