# Generated by Django 5.2.7 on 2025-11-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AddField(
            model_name='domain',
            name='doamin_date_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
