# Generated by Django 5.2.7 on 2025-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_alter_domain_options_domain_doamin_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='doamin_date_create',
            new_name='doamin_date_created',
        ),
        migrations.AddField(
            model_name='domain',
            name='doamin_date_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='doamin_date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
