# Generated by Django 5.2.7 on 2025-11-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_rename_doamin_date_create_domain_doamin_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='doamin_date_created',
            new_name='domain_date_created',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='doamin_date_expiry',
            new_name='domain_date_expiry',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='doamin_date_updated',
            new_name='domain_date_updated',
        ),
    ]
