# Generated by Django 5.2.7 on 2025-11-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_rename_doamin_date_created_domain_domain_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_name_servers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
